plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.4'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.escape.plan'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
	maven { url "https://repository.apache.org/content/repositories/releases/" }
}

ext {
	set('springAiVersion', "1.0.0-M6")
}

configurations.all {
	exclude group: 'org.slf4j', module: 'slf4j-reload4j'
}

configurations.all {
	exclude group: 'ch.qos.logback', module: 'logback-classic'
}



dependencies {
	implementation ('org.springframework.boot:spring-boot-starter-webflux')
	{
		exclude group: 'ch.qos.logback', module: 'logback-classic'
	}
	implementation 'org.springframework.boot:spring-boot-starter-websocket'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'io.projectreactor:reactor-test'
	implementation 'org.springframework.boot:spring-boot-starter-data-elasticsearch'
	implementation ('co.elastic.clients:elasticsearch-java:8.11.2')
	{
		exclude group: 'ch.qos.logback', module: 'logback-classic'
	}
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-cache'
	implementation 'org.redisson:redisson-spring-boot-starter:3.25.1'
	implementation 'org.apache.iceberg:iceberg-core:1.4.1'
	implementation 'org.apache.hadoop:hadoop-common:3.3.6'
	implementation 'org.apache.hadoop:hadoop-aws:3.3.6'
	implementation 'org.apache.iceberg:iceberg-aws:1.4.1'
	implementation 'io.minio:minio:8.5.7'
	implementation 'org.postgresql:postgresql:42.5.4'
	implementation 'org.apache.iceberg:iceberg-parquet:1.4.1'
	implementation 'org.apache.parquet:parquet-avro:1.13.1'
	implementation 'org.apache.parquet:parquet-hadoop:1.13.1'
	implementation 'software.amazon.awssdk:s3:2.20.40'
	implementation 'org.duckdb:duckdb_jdbc:0.9.2'

	implementation 'org.slf4j:slf4j-api:2.0.7'
	implementation 'org.slf4j:slf4j-simple:2.0.7'

	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
