spring.application.name=rednit
spring.data.mongodb.uri=mongodb+srv://root:root@rednit.owgpvab.mongodb.net/?retryWrites=true&w=majority&appName=Rednit
spring.data.mongodb.database=rednit
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.username=elastic
